// Issues a single license code, signed with the private key generated by
// `tool/generate_keypair.dart` (default location ~/.picturebook/private_key.bin).
//
// Usage:
//   dart run tool/issue_license.dart --customer="Wang Mei"
//   dart run tool/issue_license.dart --customer="Wang Mei" --tier=full --qr=/tmp/wang.png
//
// Output to stdout:
//   <base64url payload>.<base64url signature>
//
// You paste that into WeChat / RedNote / wherever the buyer is. The QR PNG
// (if `--qr=` was supplied) holds the same string so the buyer can scan it
// instead of typing. Either works.

import 'dart:convert';
import 'dart:io';

import 'package:cryptography/cryptography.dart';
import 'package:path/path.dart' as p;
import 'package:qr/qr.dart';

Future<int> main(List<String> args) async {
  final argMap = _parseArgs(args);
  final customer = argMap['customer'];
  if (customer == null || customer.isEmpty) {
    stderr.writeln('usage: dart run tool/issue_license.dart '
        '--customer="name or email" [--tier=full] [--qr=path.png]');
    return 2;
  }
  final tier = argMap['tier'] ?? 'full';

  // Resolve the private key. Default location matches generate_keypair.dart.
  final home = Platform.environment['HOME'] ??
      Platform.environment['USERPROFILE'];
  final defaultPath = home == null
      ? null
      : p.join(home, '.picturebook', 'private_key.bin');
  final keyPath = argMap['key'] ?? defaultPath;
  if (keyPath == null) {
    stderr.writeln('Cannot resolve --key (no HOME and no override).');
    return 2;
  }
  final keyFile = File(keyPath);
  if (!await keyFile.exists()) {
    stderr.writeln(
      'Private key not found at $keyPath.\n'
      'Run `dart run tool/generate_keypair.dart` first.',
    );
    return 2;
  }
  final privBytes = await keyFile.readAsBytes();

  // Build the payload. ISO date keeps it human-inspectable later.
  final issued = DateTime.now().toUtc().toIso8601String().substring(0, 10);
  final payload = <String, Object?>{
    'customer': customer,
    'tier': tier,
    'issued': issued,
  };
  final payloadBytes = utf8.encode(jsonEncode(payload));

  final algo = Ed25519();
  final keyPair = await algo.newKeyPairFromSeed(privBytes);
  final sig = await algo.sign(payloadBytes, keyPair: keyPair);
  final code = '${_b64(payloadBytes)}.${_b64(sig.bytes)}';

  stdout.writeln('--- Picture Book license code ---');
  stdout.writeln('customer : $customer');
  stdout.writeln('tier     : $tier');
  stdout.writeln('issued   : $issued');
  stdout.writeln();
  stdout.writeln(code);
  stdout.writeln();

  // Optional: render a scannable PNG. QR error-correction at M is a good
  // trade-off between density and tolerance to a phone-camera scan.
  final qrPath = argMap['qr'];
  if (qrPath != null && qrPath.isNotEmpty) {
    final qr = QrCode.fromData(
      data: code,
      errorCorrectLevel: QrErrorCorrectLevel.M,
    );
    final image = QrImage(qr);
    // Render as PBM (portable bitmap) — no external image lib needed.
    // Most viewers and WeChat scan PBMs fine; if not, convert via `sips`:
    //   sips -s format png file.pbm --out file.png
    const scale = 8;
    final size = image.moduleCount;
    final width = size * scale;
    final height = size * scale;
    final out = StringBuffer()
      ..writeln('P1')
      ..writeln('# Picture Book license QR')
      ..writeln('$width $height');
    for (var y = 0; y < height; y++) {
      for (var x = 0; x < width; x++) {
        final on = image.isDark(y ~/ scale, x ~/ scale);
        out.write(on ? '1 ' : '0 ');
      }
      out.writeln();
    }
    final dest = File(qrPath);
    await dest.parent.create(recursive: true);
    await dest.writeAsString(out.toString());
    stdout.writeln('QR written to ${dest.path} (PBM format).');
    stdout.writeln(
      'Convert to PNG if needed:  sips -s format png ${dest.path} '
      '--out ${p.withoutExtension(dest.path)}.png',
    );
  }
  return 0;
}

String _b64(List<int> bytes) =>
    base64Url.encode(bytes).replaceAll('=', '');

Map<String, String> _parseArgs(List<String> args) {
  final out = <String, String>{};
  for (final arg in args) {
    if (!arg.startsWith('--')) continue;
    final eq = arg.indexOf('=');
    if (eq < 0) continue;
    out[arg.substring(2, eq)] = arg.substring(eq + 1);
  }
  return out;
}
